// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xelaffizgghzchdwagjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbGFmZml6Z2doemNoZHdhZ2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0ODgwNDMsImV4cCI6MjA1NjA2NDA0M30.j5n_KowPEpO0W0tlzCQHw6uVNyKAxy8ITehzd3sBOjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);